documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.spec.ts"
          - "**/*.spec.tsx"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "package.json"
          - "pnpm-lock.yaml"
          - "renovate.json"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "Dockerfile"
          - "docker/**"
          - ".dockerignore"

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.config.*"
          - "tsconfig*.json"
          - ".eslintrc*"
          - "eslint.config.*"
          - "cliff.toml"
