export const ToolId = {
  Case: 'case',
  Slug: 'slug',
  Lorem: 'lorem',
  Regex: 'regex',
  TextDiff: 'text-diff',
  Numeronym: 'numeronym',
  TextStats: 'text-stats',
  Nato: 'nato',
  Json: 'json',
  JsonDiff: 'json-diff',
  Yaml: 'yaml',
  JsonCsv: 'json-csv',
  Base64: 'base64',
  Url: 'url',
  Html: 'html',
  Jwt: 'jwt',
  Hash: 'hash',
  Uuid: 'uuid',
  Ulid: 'ulid',
  Password: 'password',
  Totp: 'totp',
  Crontab: 'crontab',
  Qr: 'qr',
  Timestamp: 'timestamp',
  Color: 'color',
  Base: 'base',
  Chmod: 'chmod',
  Iban: 'iban',
  Roman: 'roman',
  Subnet: 'subnet',
  HttpStatus: 'http-status',
  IpAddress: 'ip-address',
  Cypher: 'cypher',
  Bcrypt: 'bcrypt',
  Hmac: 'hmac',
  PasswordStrength: 'password-strength',
  Bip39: 'bip39',
  RsaKeypair: 'rsa-keypair',
  IpRange: 'ip-range',
  MacGenerator: 'mac-generator',
  MacLookup: 'mac-lookup',
  Ipv6Ula: 'ipv6-ula',
  MathEvaluator: 'math-evaluator',
  Percentage: 'percentage',
  Eta: 'eta',
  Temperature: 'temperature',
  WifiQr: 'wifi-qr',
  SvgPlaceholder: 'svg-placeholder',
  UrlParser: 'url-parser',
  BasicAuth: 'basic-auth',
  MetaTags: 'meta-tags',
  MimeTypes: 'mime-types',
  Keycode: 'keycode',
  UserAgent: 'user-agent',
  Safelink: 'safelink',
  DeviceInfo: 'device-info',
  RandomPort: 'random-port',
  EmailNormalizer: 'email-normalizer',
  XmlFormatter: 'xml-formatter',
  SqlPrettifier: 'sql-prettifier',
  DockerCompose: 'docker-compose',
  GitCheatsheet: 'git-cheatsheet',
  RegexCheatsheet: 'regex-cheatsheet',
  TextBinary: 'text-binary',
  TextUnicode: 'text-unicode',
  ListConverter: 'list-converter',
  MarkdownHtml: 'markdown-html',
  XmlJson: 'xml-json',
  TomlJson: 'toml-json',
  TomlYaml: 'toml-yaml',
  Base64File: 'base64-file',
  StringObfuscator: 'string-obfuscator',
  AsciiDrawer: 'ascii-drawer',
  EmojiPicker: 'emoji-picker',
  PhoneParser: 'phone-parser',
} as const;

export type ToolId = (typeof ToolId)[keyof typeof ToolId];

export const ALL_TOOL_IDS = Object.values(ToolId);

export const ToolCategoryId = {
  Text: 'text',
  Data: 'data',
  Encoding: 'encoding',
  Generators: 'generators',
  Converters: 'converters',
  Network: 'network',
  Crypto: 'crypto',
  Web: 'web',
  Development: 'development',
  Math: 'math',
  Measurement: 'measurement',
  Images: 'images',
} as const;

export type ToolCategoryId =
  (typeof ToolCategoryId)[keyof typeof ToolCategoryId];
